language: node_js

node_js:
  - 6
  - 8
  - 10

script:
- npm test
- npm run coverage
- cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage

cache:
  yarn: true

env:
  global:
    secure: jt32uur2Bsx44QcPYzUXv5Y0K3TVQxujGB/RqZv4dN/ld/jDjSKGGb6O4l5XawR9UNhVxplKPlcQS8tjDA13N7VE6ocdMNDdwUnkMLmJnokq24CpEgRP7LWgHjIT6HIHzA42+dWAjZt/jf1NKTtYqouMCnLQXmh6Gp+lGMvRgx7Fy408ldHNiGg6glneBlkgLbrqg968oMFAP2M4begeIUds+nwkHX6knQgzBgSk5tjnPjcWEOsN3u6rfcf+WlsvNYbVPhnp+vgWritpZvXjXqP/IlryEPjh9Wr/LZORXVF0Do3/Yad3b3Jc/yWWgqXO8qNbkEmVnG6azByIimBCzoOStCyQIIGzicFlY3HwBY9TuB40MG4OQbGHTi3RjS3YOyglgjxUG24Hdk1jBPbmWitvSOSZC664sQ4/xJZmXhFrG1btyGlRNIgwKwSHC1vBiMQDWdYf4Ef3ALYo1xFlqncRE0F0svcs27ebOunHgS2o7K68f9hcjsxRjyGwxAElf7TcbguS/aPqsWjRbzKDxrB7WEyK9GflEF5hVHw1Nnbh7Z3xOlejsjolONFaYmzQVWe0vQjlnVuDyP7Zsl44KbCSHsPCFZOnuz3xRq8Ox8EnGqbO6kZyqzewjU6c4pZ5K7Y1f6QEJuU4x0ALcS881EER9Q9v+9vnLTPW1lOu6Ns=
